apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  location.list: |-
    location /healthz {
      return 200 'OK';
    }
    location /channel/v3/ {
      set $target http://content-service.knowlg-api.svc.cluster.local:9000;
      rewrite ^/channel/v3/(.*) /channel/v3/$1 break;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_pass $target;
    }
    location /license/v3/ {
      set $target http://content-service.knowlg-api.svc.cluster.local:9000;
      rewrite ^/license/v3/(.*) /license/v3/$1 break;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_pass $target;
    }
    location /asset/v4/ {
      set $target http://content-service.knowlg-api.svc.cluster.local:9000;
      rewrite ^/asset/v4/(.*) /asset/v4/$1 break;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_pass $target;
    }
    location /content/v4/ {
      set $target http://content-service.knowlg-api.svc.cluster.local:9000;
      rewrite ^/content/v4/(.*) /content/v4/$1 break;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_pass $target;
    }
    location /collection/v4/ {
      set $target http://content-service.knowlg-api.svc.cluster.local:9000;
      rewrite ^/collection/v4/(.*) /collection/v4/$1 break;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_pass $target;
    }
  sites.conf: |-
    # Ref: https://github.com/openresty/openresty/#resolvconf-parsing
    resolver local=on;
    # Need real ip address for flags in replay.
    # Some LBs will forward real ips as x-forwarded-for
    # So making that as priority
    map $http_x_forwarded_for $real_ip {
        ~^(\d+\.\d+\.\d+\.\d+) $1;
        default $remote_addr;
    }
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      # server_name _;
      include /etc/nginx/conf.d/location.list;
    }