apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-storage
  labels:
    app.kubernetes.io/component: neo4j
    app.kubernetes.io/instance: neo4j
    app.kubernetes.io/name: neo4j
  annotations: {}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-claim
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
