apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-claim
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations: 
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
